apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce-dev
type: Opaque
data:
  # postgres (base64 encoded)
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce-dev
type: Opaque
data:
  # dev-jwt-secret-key-12345 (base64 encoded)
  jwt-secret: ZGV2LWp3dC1zZWNyZXQta2V5LTEyMzQ1
